//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KQStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD
    {
        public int AdsId { get; set; }
        public string AdsName { get; set; }
        public string AdsDetail { get; set; }
        public string AdsImage { get; set; }
    }
}
